import os

# Telegram Bot Credentials
BOT_TOKEN = "8573297005:AAGxtvO9U50aULxzpS1nDKHJxKnXa6fxeoE"
OWNER_ID = 5695882571

# Conversation States
(WAIT_MAT_FILE, WAIT_MAT_NAME, WAIT_CAT_NAME, WAIT_USER_ID, WAIT_REM_USER,
 WAIT_ADMIN_ID, WAIT_REM_ADMIN, WAIT_BROADCAST, WAIT_SUPPORT_UNAME,
 WAIT_SUPPORT_LINK, WAIT_SUPPORT_TEXT, WAIT_EDIT_NAME, WAIT_EDIT_FILE) = range(13)
