import os

# Telegram Bot Credentials (Ye wahi rahenge jo tune fix kiye the)
BOT_TOKEN = "8573297005:AAFjbDHMUDC5jmC0M6YHJRizD73ytucvg0g"
OWNER_ID = 5695882571

# Conversation States (Inko badha diya gaya hai)
(
    WAIT_MAT_FILE, WAIT_MAT_NAME, WAIT_CAT_NAME,
    WAIT_USER_ID, WAIT_REM_USER, WAIT_ADMIN_ID, WAIT_REM_ADMIN,
    WAIT_BROADCAST, WAIT_SUPPORT_UNAME, WAIT_SUPPORT_LINK, WAIT_SUPPORT_TEXT,
    WAIT_ADD_MAT_CAT, WAIT_DEL_MAT_CAT, WAIT_DEL_MAT_NAME, WAIT_DEL_CONFIRM,
    WAIT_EDIT_MAT_CAT, WAIT_EDIT_MAT_NAME, WAIT_EDIT_ACTION,
    WAIT_EDIT_NAME_NEW, WAIT_EDIT_FILE_NEW, WAIT_EDIT_MOVE_CAT
) = range(21)
